#!/usr/bin/env python3
"""
Add sample quiz questions directly to database
"""

import sys
import os
from datetime import datetime
from sqlalchemy.orm import Session

# Add the app directory to the path
sys.path.append(os.path.join(os.path.dirname(__file__), 'app'))

from app.db.session import SessionLocal
from app.models.question import Question

def add_sample_questions():
    """Add sample quiz questions to database"""
    print("🚀 Adding sample quiz questions...")
    
    db = SessionLocal()
    
    try:
        # Physics questions for Grade 9
        questions = [
            {
                "subject": "physics",
                "grade": 9,
                "topic": "Force and Motion",
                "question_text": "What is Newton's First Law of Motion?",
                "question_text_bangla": "নিউটনের প্রথম গতিসূত্র কী?",
                "option_a": "An object at rest stays at rest unless acted upon by a force",
                "option_b": "Force equals mass times acceleration",
                "option_c": "For every action there is an equal and opposite reaction",
                "option_d": "Energy cannot be created or destroyed",
                "option_a_bangla": "একটি স্থির বস্তু বল প্রয়োগ না করা পর্যন্ত স্থির থাকে",
                "option_b_bangla": "বল = ভর × ত্বরণ",
                "option_c_bangla": "প্রতিটি ক্রিয়ার একটি সমান ও বিপরীত প্রতিক্রিয়া আছে",
                "option_d_bangla": "শক্তি সৃষ্টি বা ধ্বংস করা যায় না",
                "correct_answer": "A",
                "difficulty_level": 1,
                "bloom_level": 2,
                "explanation": "Newton's First Law states that an object at rest stays at rest and an object in motion stays in motion unless acted upon by an external force.",
                "explanation_bangla": "নিউটনের প্রথম সূত্র বলে যে একটি স্থির বস্তু স্থির থাকে এবং গতিশীল বস্তু গতিশীল থাকে যতক্ষণ না বাহ্যিক বল প্রয়োগ করা হয়।"
            },
            {
                "subject": "physics",
                "grade": 9,
                "topic": "Force and Motion",
                "question_text": "If a car accelerates at 2 m/s² and has a mass of 1000 kg, what is the net force?",
                "question_text_bangla": "যদি একটি গাড়ি ২ মি/সে² ত্বরণে চলে এবং এর ভর ১০০০ কেজি হয়, তাহলে নিট বল কত?",
                "option_a": "500 N",
                "option_b": "1000 N", 
                "option_c": "2000 N",
                "option_d": "4000 N",
                "option_a_bangla": "৫০০ নিউটন",
                "option_b_bangla": "১০০০ নিউটন",
                "option_c_bangla": "২০০০ নিউটন",
                "option_d_bangla": "৪০০০ নিউটন",
                "correct_answer": "C",
                "difficulty_level": 3,
                "bloom_level": 3,
                "explanation": "Using F = ma, Force = 1000 kg × 2 m/s² = 2000 N",
                "explanation_bangla": "F = ma সূত্র ব্যবহার করে, বল = ১০০০ কেজি × ২ মি/সে² = ২০০০ নিউটন"
            },
            {
                "subject": "mathematics",
                "grade": 9,
                "topic": "Algebra",
                "question_text": "Solve for x: 2x + 5 = 13",
                "question_text_bangla": "x এর মান নির্ণয় করো: 2x + 5 = 13",
                "option_a": "x = 3",
                "option_b": "x = 4",
                "option_c": "x = 5",
                "option_d": "x = 6",
                "option_a_bangla": "x = ৩",
                "option_b_bangla": "x = ৪",
                "option_c_bangla": "x = ৫",
                "option_d_bangla": "x = ৬",
                "correct_answer": "B",
                "difficulty_level": 1,
                "bloom_level": 3,
                "explanation": "2x + 5 = 13, so 2x = 8, therefore x = 4",
                "explanation_bangla": "2x + 5 = 13, সুতরাং 2x = 8, অতএব x = 4"
            },
            {
                "subject": "mathematics",
                "grade": 9,
                "topic": "Geometry",
                "question_text": "What is the area of a triangle with base 6 cm and height 8 cm?",
                "question_text_bangla": "৬ সেমি ভূমি এবং ৮ সেমি উচ্চতাবিশিষ্ট ত্রিভুজের ক্ষেত্রফল কত?",
                "option_a": "24 cm²",
                "option_b": "48 cm²",
                "option_c": "14 cm²",
                "option_d": "30 cm²",
                "option_a_bangla": "২৪ বর্গ সেমি",
                "option_b_bangla": "৪৮ বর্গ সেমি",
                "option_c_bangla": "১৪ বর্গ সেমি",
                "option_d_bangla": "৩০ বর্গ সেমি",
                "correct_answer": "A",
                "difficulty_level": 1,
                "bloom_level": 3,
                "explanation": "Area of triangle = (1/2) × base × height = (1/2) × 6 × 8 = 24 cm²",
                "explanation_bangla": "ত্রিভুজের ক্ষেত্রফল = (১/২) × ভূমি × উচ্চতা = (১/২) × ৬ × ৮ = ২৪ বর্গ সেমি"
            },
            {
                "subject": "chemistry",
                "grade": 9,
                "topic": "Atomic Structure",
                "question_text": "What is the atomic number of Carbon?",
                "question_text_bangla": "কার্বনের পারমাণবিক সংখ্যা কত?",
                "option_a": "4",
                "option_b": "6",
                "option_c": "8",
                "option_d": "12",
                "option_a_bangla": "৪",
                "option_b_bangla": "৬",
                "option_c_bangla": "৮",
                "option_d_bangla": "১২",
                "correct_answer": "B",
                "difficulty_level": 1,
                "bloom_level": 1,
                "explanation": "Carbon has 6 protons, so its atomic number is 6",
                "explanation_bangla": "কার্বনে ৬টি প্রোটন আছে, তাই এর পারমাণবিক সংখ্যা ৬"
            },
            {
                "subject": "biology",
                "grade": 9,
                "topic": "Cell Biology",
                "question_text": "What is the powerhouse of the cell?",
                "question_text_bangla": "কোশের শক্তিঘর কোনটি?",
                "option_a": "Nucleus",
                "option_b": "Mitochondria",
                "option_c": "Ribosome",
                "option_d": "Chloroplast",
                "option_a_bangla": "নিউক্লিয়াস",
                "option_b_bangla": "মাইটোকন্ড্রিয়া",
                "option_c_bangla": "রাইবোসোম",
                "option_d_bangla": "ক্লোরোপ্লাস্ট",
                "correct_answer": "B",
                "difficulty_level": 1,
                "bloom_level": 1,
                "explanation": "Mitochondria produces ATP, the energy currency of the cell",
                "explanation_bangla": "মাইটোকন্ড্রিয়া ATP তৈরি করে, যা কোশের শক্তির মুদ্রা"
            },
            {
                "subject": "english",
                "grade": 9,
                "topic": "Grammar",
                "question_text": "Which is the correct past tense of 'go'?",
                "question_text_bangla": "'go' এর সঠিক অতীত কাল কোনটি?",
                "option_a": "goed",
                "option_b": "went",
                "option_c": "gone",
                "option_d": "going",
                "option_a_bangla": "goed",
                "option_b_bangla": "went",
                "option_c_bangla": "gone",
                "option_d_bangla": "going",
                "correct_answer": "B",
                "difficulty_level": 1,
                "bloom_level": 1,
                "explanation": "The past tense of 'go' is 'went'",
                "explanation_bangla": "'go' এর অতীত কাল হলো 'went'"
            },
            {
                "subject": "bangla",
                "grade": 9,
                "topic": "ব্যাকরণ",
                "question_text": "'সূর্য' শব্দের সমার্থক শব্দ কোনটি?",
                "question_text_bangla": "'সূর্য' শব্দের সমার্থক শব্দ কোনটি?",
                "option_a": "চাঁদ",
                "option_b": "রবি",
                "option_c": "তারা",
                "option_d": "গ্রহ",
                "option_a_bangla": "চাঁদ",
                "option_b_bangla": "রবি",
                "option_c_bangla": "তারা",
                "option_d_bangla": "গ্রহ",
                "correct_answer": "B",
                "difficulty_level": 1,
                "bloom_level": 1,
                "explanation": "'রবি' is a synonym for 'সূর্য' (sun)",
                "explanation_bangla": "'রবি' হলো 'সূর্য' এর সমার্থক শব্দ"
            },
            # Additional questions to meet minimum requirement of 5 per subject
            {
                "subject": "mathematics",
                "grade": 9,
                "topic": "Algebra",
                "question_text": "What is the value of x in: 3x - 7 = 14?",
                "question_text_bangla": "3x - 7 = 14 সমীকরণে x এর মান কত?",
                "option_a": "x = 5",
                "option_b": "x = 6",
                "option_c": "x = 7",
                "option_d": "x = 8",
                "option_a_bangla": "x = ৫",
                "option_b_bangla": "x = ৬",
                "option_c_bangla": "x = ৭",
                "option_d_bangla": "x = ৮",
                "correct_answer": "C",
                "difficulty_level": 2,
                "bloom_level": 3,
                "explanation": "3x - 7 = 14, so 3x = 21, therefore x = 7",
                "explanation_bangla": "3x - 7 = 14, সুতরাং 3x = 21, অতএব x = 7"
            },
            {
                "subject": "mathematics",
                "grade": 9,
                "topic": "Geometry",
                "question_text": "What is the perimeter of a rectangle with length 8 cm and width 5 cm?",
                "question_text_bangla": "৮ সেমি দৈর্ঘ্য এবং ৫ সেমি প্রস্থবিশিষ্ট আয়তক্ষেত্রের পরিসীমা কত?",
                "option_a": "13 cm",
                "option_b": "26 cm",
                "option_c": "40 cm",
                "option_d": "18 cm",
                "option_a_bangla": "১৩ সেমি",
                "option_b_bangla": "২৬ সেমি",
                "option_c_bangla": "৪০ সেমি",
                "option_d_bangla": "১৮ সেমি",
                "correct_answer": "B",
                "difficulty_level": 1,
                "bloom_level": 3,
                "explanation": "Perimeter = 2(length + width) = 2(8 + 5) = 26 cm",
                "explanation_bangla": "পরিসীমা = ২(দৈর্ঘ্য + প্রস্থ) = ২(৮ + ৫) = ২৬ সেমি"
            },
            {
                "subject": "mathematics",
                "grade": 9,
                "topic": "Numbers",
                "question_text": "What is 15% of 200?",
                "question_text_bangla": "২০০ এর ১৫% কত?",
                "option_a": "25",
                "option_b": "30",
                "option_c": "35",
                "option_d": "40",
                "option_a_bangla": "২৫",
                "option_b_bangla": "৩০",
                "option_c_bangla": "৩৫",
                "option_d_bangla": "৪০",
                "correct_answer": "B",
                "difficulty_level": 2,
                "bloom_level": 3,
                "explanation": "15% of 200 = (15/100) × 200 = 30",
                "explanation_bangla": "২০০ এর ১৫% = (১৫/১০০) × ২০০ = ৩০"
            },
            {
                "subject": "physics",
                "grade": 9,
                "topic": "Energy",
                "question_text": "What type of energy does a moving car have?",
                "question_text_bangla": "চলমান গাড়ির কী ধরনের শক্তি আছে?",
                "option_a": "Potential Energy",
                "option_b": "Kinetic Energy",
                "option_c": "Chemical Energy",
                "option_d": "Nuclear Energy",
                "option_a_bangla": "স্থিতিশক্তি",
                "option_b_bangla": "গতিশক্তি",
                "option_c_bangla": "রাসায়নিক শক্তি",
                "option_d_bangla": "পারমাণবিক শক্তি",
                "correct_answer": "B",
                "difficulty_level": 1,
                "bloom_level": 2,
                "explanation": "A moving object has kinetic energy due to its motion",
                "explanation_bangla": "চলমান বস্তুর গতির কারণে গতিশক্তি থাকে"
            },
            {
                "subject": "physics",
                "grade": 9,
                "topic": "Light",
                "question_text": "What happens when light passes from air to water?",
                "question_text_bangla": "আলো বাতাস থেকে পানিতে গেলে কী ঘটে?",
                "option_a": "It speeds up",
                "option_b": "It slows down",
                "option_c": "It stops",
                "option_d": "Nothing changes",
                "option_a_bangla": "এটি দ্রুত হয়",
                "option_b_bangla": "এটি ধীর হয়",
                "option_c_bangla": "এটি থেমে যায়",
                "option_d_bangla": "কিছুই পরিবর্তন হয় না",
                "correct_answer": "B",
                "difficulty_level": 2,
                "bloom_level": 2,
                "explanation": "Light slows down when it enters a denser medium like water",
                "explanation_bangla": "আলো ঘন মাধ্যম যেমন পানিতে প্রবেশ করলে ধীর হয়ে যায়"
            },
            {
                "subject": "physics",
                "grade": 9,
                "topic": "Sound",
                "question_text": "Sound travels fastest in which medium?",
                "question_text_bangla": "শব্দ কোন মাধ্যমে সবচেয়ে দ্রুত চলে?",
                "option_a": "Air",
                "option_b": "Water",
                "option_c": "Steel",
                "option_d": "Vacuum",
                "option_a_bangla": "বাতাস",
                "option_b_bangla": "পানি",
                "option_c_bangla": "ইস্পাত",
                "option_d_bangla": "শূন্যস্থান",
                "correct_answer": "C",
                "difficulty_level": 2,
                "bloom_level": 2,
                "explanation": "Sound travels fastest in solids like steel due to tightly packed molecules",
                "explanation_bangla": "অণুগুলো ঘনভাবে সাজানো থাকায় ইস্পাতের মতো কঠিন পদার্থে শব্দ সবচেয়ে দ্রুত চলে"
            },
            {
                "subject": "chemistry",
                "grade": 9,
                "topic": "Periodic Table",
                "question_text": "Which element has the symbol 'O'?",
                "question_text_bangla": "কোন মৌলের প্রতীক 'O'?",
                "option_a": "Gold",
                "option_b": "Oxygen",
                "option_c": "Silver",
                "option_d": "Iron",
                "option_a_bangla": "সোনা",
                "option_b_bangla": "অক্সিজেন",
                "option_c_bangla": "রূপা",
                "option_d_bangla": "লোহা",
                "correct_answer": "B",
                "difficulty_level": 1,
                "bloom_level": 1,
                "explanation": "Oxygen has the chemical symbol 'O'",
                "explanation_bangla": "অক্সিজেনের রাসায়নিক প্রতীক 'O'"
            },
            {
                "subject": "chemistry",
                "grade": 9,
                "topic": "Chemical Reactions",
                "question_text": "What is produced when hydrogen burns in oxygen?",
                "question_text_bangla": "হাইড্রোজেন অক্সিজেনে পুড়লে কী উৎপন্ন হয়?",
                "option_a": "Carbon dioxide",
                "option_b": "Water",
                "option_c": "Hydrogen peroxide",
                "option_d": "Ozone",
                "option_a_bangla": "কার্বন ডাইঅক্সাইড",
                "option_b_bangla": "পানি",
                "option_c_bangla": "হাইড্রোজেন পারঅক্সাইড",
                "option_d_bangla": "ওজোন",
                "correct_answer": "B",
                "difficulty_level": 2,
                "bloom_level": 3,
                "explanation": "2H₂ + O₂ → 2H₂O (water is formed)",
                "explanation_bangla": "2H₂ + O₂ → 2H₂O (পানি তৈরি হয়)"
            },
            {
                "subject": "chemistry",
                "grade": 9,
                "topic": "States of Matter",
                "question_text": "At what temperature does water boil at sea level?",
                "question_text_bangla": "সমুদ্রপৃষ্ঠে পানি কত তাপমাত্রায় ফুটে?",
                "option_a": "90°C",
                "option_b": "95°C",
                "option_c": "100°C",
                "option_d": "105°C",
                "option_a_bangla": "৯০°সে",
                "option_b_bangla": "৯৫°সে",
                "option_c_bangla": "১০০°সে",
                "option_d_bangla": "১০৫°সে",
                "correct_answer": "C",
                "difficulty_level": 1,
                "bloom_level": 1,
                "explanation": "Water boils at 100°C (212°F) at sea level pressure",
                "explanation_bangla": "সমুদ্রপৃষ্ঠের চাপে পানি ১০০°সে তাপমাত্রায় ফুটে"
            },
            {
                "subject": "biology",
                "grade": 9,
                "topic": "Photosynthesis",
                "question_text": "What gas do plants release during photosynthesis?",
                "question_text_bangla": "সালোকসংশ্লেষণের সময় উদ্ভিদ কোন গ্যাস নিঃসরণ করে?",
                "option_a": "Carbon dioxide",
                "option_b": "Nitrogen",
                "option_c": "Oxygen",
                "option_d": "Hydrogen",
                "option_a_bangla": "কার্বন ডাইঅক্সাইড",
                "option_b_bangla": "নাইট্রোজেন",
                "option_c_bangla": "অক্সিজেন",
                "option_d_bangla": "হাইড্রোজেন",
                "correct_answer": "C",
                "difficulty_level": 1,
                "bloom_level": 2,
                "explanation": "Plants release oxygen as a byproduct of photosynthesis",
                "explanation_bangla": "সালোকসংশ্লেষণের উপজাত হিসেবে উদ্ভিদ অক্সিজেন নিঃসরণ করে"
            },
            {
                "subject": "biology",
                "grade": 9,
                "topic": "Human Body",
                "question_text": "Which organ pumps blood throughout the body?",
                "question_text_bangla": "কোন অঙ্গ সারা শরীরে রক্ত পাম্প করে?",
                "option_a": "Liver",
                "option_b": "Lungs",
                "option_c": "Heart",
                "option_d": "Kidney",
                "option_a_bangla": "যকৃত",
                "option_b_bangla": "ফুসফুস",
                "option_c_bangla": "হৃদয়",
                "option_d_bangla": "কিডনি",
                "correct_answer": "C",
                "difficulty_level": 1,
                "bloom_level": 1,
                "explanation": "The heart is a muscular organ that pumps blood throughout the body",
                "explanation_bangla": "হৃদয় একটি পেশীবহুল অঙ্গ যা সারা শরীরে রক্ত পাম্প করে"
            },
            {
                "subject": "biology",
                "grade": 9,
                "topic": "Genetics",
                "question_text": "What is the basic unit of heredity?",
                "question_text_bangla": "বংশগতির মৌলিক একক কী?",
                "option_a": "Cell",
                "option_b": "Gene",
                "option_c": "Chromosome",
                "option_d": "DNA",
                "option_a_bangla": "কোশ",
                "option_b_bangla": "জিন",
                "option_c_bangla": "ক্রোমোজোম",
                "option_d_bangla": "ডিএনএ",
                "correct_answer": "B",
                "difficulty_level": 2,
                "bloom_level": 2,
                "explanation": "A gene is the basic unit of heredity that carries genetic information",
                "explanation_bangla": "জিন হলো বংশগতির মৌলিক একক যা জিনগত তথ্য বহন করে"
            },
            {
                "subject": "english",
                "grade": 9,
                "topic": "Vocabulary",
                "question_text": "What is the opposite of 'ancient'?",
                "question_text_bangla": "'ancient' এর বিপরীত শব্দ কী?",
                "option_a": "old",
                "option_b": "modern",
                "option_c": "historic",
                "option_d": "traditional",
                "option_a_bangla": "old",
                "option_b_bangla": "modern",
                "option_c_bangla": "historic",
                "option_d_bangla": "traditional",
                "correct_answer": "B",
                "difficulty_level": 1,
                "bloom_level": 2,
                "explanation": "Modern is the opposite of ancient",
                "explanation_bangla": "Modern হলো ancient এর বিপরীত শব্দ"
            },
            {
                "subject": "english",
                "grade": 9,
                "topic": "Literature",
                "question_text": "Who wrote 'Romeo and Juliet'?",
                "question_text_bangla": "'Romeo and Juliet' কে লিখেছেন?",
                "option_a": "Charles Dickens",
                "option_b": "William Shakespeare",
                "option_c": "Jane Austen",
                "option_d": "Mark Twain",
                "option_a_bangla": "Charles Dickens",
                "option_b_bangla": "William Shakespeare",
                "option_c_bangla": "Jane Austen",
                "option_d_bangla": "Mark Twain",
                "correct_answer": "B",
                "difficulty_level": 1,
                "bloom_level": 1,
                "explanation": "William Shakespeare wrote the famous play 'Romeo and Juliet'",
                "explanation_bangla": "William Shakespeare বিখ্যাত নাটক 'Romeo and Juliet' লিখেছেন"
            },
            {
                "subject": "english",
                "grade": 9,
                "topic": "Grammar",
                "question_text": "Which sentence is grammatically correct?",
                "question_text_bangla": "কোন বাক্যটি ব্যাকরণগতভাবে সঠিক?",
                "option_a": "She don't like apples",
                "option_b": "She doesn't like apples",
                "option_c": "She not like apples",
                "option_d": "She no like apples",
                "option_a_bangla": "She don't like apples",
                "option_b_bangla": "She doesn't like apples",
                "option_c_bangla": "She not like apples",
                "option_d_bangla": "She no like apples",
                "correct_answer": "B",
                "difficulty_level": 1,
                "bloom_level": 3,
                "explanation": "With third person singular, we use 'doesn't' not 'don't'",
                "explanation_bangla": "তৃতীয় পুরুষ একবচনের সাথে 'doesn't' ব্যবহার করি, 'don't' নয়"
            },
            {
                "subject": "bangla",
                "grade": 9,
                "topic": "সাহিত্য",
                "question_text": "'পদ্মা নদীর মাঝি' উপন্যাসের লেখক কে?",
                "question_text_bangla": "'পদ্মা নদীর মাঝি' উপন্যাসের লেখক কে?",
                "option_a": "রবীন্দ্রনাথ ঠাকুর",
                "option_b": "মানিক বন্দ্যোপাধ্যায়",
                "option_c": "শরৎচন্দ্র চট্টোপাধ্যায়",
                "option_d": "বিভূতিভূষণ বন্দ্যোপাধ্যায়",
                "option_a_bangla": "রবীন্দ্রনাথ ঠাকুর",
                "option_b_bangla": "মানিক বন্দ্যোপাধ্যায়",
                "option_c_bangla": "শরৎচন্দ্র চট্টোপাধ্যায়",
                "option_d_bangla": "বিভূতিভূষণ বন্দ্যোপাধ্যায়",
                "correct_answer": "B",
                "difficulty_level": 2,
                "bloom_level": 1,
                "explanation": "মানিক বন্দ্যোপাধ্যায় 'পদ্মা নদীর মাঝি' উপন্যাসের লেখক",
                "explanation_bangla": "মানিক বন্দ্যোপাধ্যায় 'পদ্মা নদীর মাঝি' উপন্যাসের লেখক"
            },
            {
                "subject": "bangla",
                "grade": 9,
                "topic": "ব্যাকরণ",
                "question_text": "'বিদ্যা' শব্দের বিশেষণ কোনটি?",
                "question_text_bangla": "'বিদ্যা' শব্দের বিশেষণ কোনটি?",
                "option_a": "বিদ্বান",
                "option_b": "বিদ্যালয়",
                "option_c": "বিদ্যার্থী",
                "option_d": "বিদ্যুৎ",
                "option_a_bangla": "বিদ্বান",
                "option_b_bangla": "বিদ্যালয়",
                "option_c_bangla": "বিদ্যার্থী",
                "option_d_bangla": "বিদ্যুৎ",
                "correct_answer": "A",
                "difficulty_level": 2,
                "bloom_level": 2,
                "explanation": "'বিদ্বান' হলো 'বিদ্যা' শব্দের বিশেষণ রূপ",
                "explanation_bangla": "'বিদ্বান' হলো 'বিদ্যা' শব্দের বিশেষণ রূপ"
            },
            {
                "subject": "bangla",
                "grade": 9,
                "topic": "কবিতা",
                "question_text": "'আমার সোনার বাংলা' গানের রচয়িতা কে?",
                "question_text_bangla": "'আমার সোনার বাংলা' গানের রচয়িতা কে?",
                "option_a": "কাজী নজরুল ইসলাম",
                "option_b": "রবীন্দ্রনাথ ঠাকুর",
                "option_c": "জীবনানন্দ দাশ",
                "option_d": "সুকান্ত ভট্টাচার্য",
                "option_a_bangla": "কাজী নজরুল ইসলাম",
                "option_b_bangla": "রবীন্দ্রনাথ ঠাকুর",
                "option_c_bangla": "জীবনানন্দ দাশ",
                "option_d_bangla": "সুকান্ত ভট্টাচার্য",
                "correct_answer": "B",
                "difficulty_level": 1,
                "bloom_level": 1,
                "explanation": "রবীন্দ্রনাথ ঠাকুর 'আমার সোনার বাংলা' গানের রচয়িতা",
                "explanation_bangla": "রবীন্দ্রনাথ ঠাকুর 'আমার সোনার বাংলা' গানের রচয়িতা"
            }
        ]
        
        created_count = 0
        
        for q_data in questions:
            # Check if question already exists
            existing_q = db.query(Question).filter(
                Question.question_text == q_data["question_text"]
            ).first()
            if existing_q:
                print(f"⚠️  Question already exists: {q_data['question_text'][:50]}...")
                continue
                
            question = Question(
                subject=q_data["subject"],
                grade=q_data["grade"],
                topic=q_data["topic"],
                question_text=q_data["question_text"],
                question_text_bangla=q_data["question_text_bangla"],
                option_a=q_data["option_a"],
                option_b=q_data["option_b"],
                option_c=q_data["option_c"],
                option_d=q_data["option_d"],
                option_a_bangla=q_data["option_a_bangla"],
                option_b_bangla=q_data["option_b_bangla"],
                option_c_bangla=q_data["option_c_bangla"],
                option_d_bangla=q_data["option_d_bangla"],
                correct_answer=q_data["correct_answer"],
                difficulty_level=q_data["difficulty_level"],
                bloom_level=q_data["bloom_level"],
                explanation=q_data["explanation"],
                explanation_bangla=q_data["explanation_bangla"],
                is_active=True,
                created_at=datetime.utcnow()
            )
            db.add(question)
            created_count += 1
            print(f"✅ Added: {question.subject} - {question.question_text[:50]}...")
        
        db.commit()
        
        print(f"\\n📊 Summary: Added {created_count} new questions")
        print("\\n🎯 Questions by Subject:")
        
        # Count questions by subject
        subjects = db.query(Question.subject).distinct().all()
        for (subject,) in subjects:
            count = db.query(Question).filter(Question.subject == subject).count()
            print(f"   {subject}: {count} questions")
            
    except Exception as e:
        print(f"❌ Error adding questions: {e}")
        db.rollback()
        raise
    finally:
        db.close()

if __name__ == "__main__":
    add_sample_questions()