"""add_questions_and_quizzes_tables

Revision ID: 85fe462cda59
Revises: create_assessment_tables
Create Date: 2025-12-19 16:45:59.832992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85fe462cda59'
down_revision = 'create_assessment_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_text_bangla', sa.Text(), nullable=True),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('option_a_bangla', sa.Text(), nullable=True),
    sa.Column('option_b_bangla', sa.Text(), nullable=True),
    sa.Column('option_c_bangla', sa.Text(), nullable=True),
    sa.Column('option_d_bangla', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('explanation_bangla', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('subtopic', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('bloom_level', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('chapter', sa.String(length=100), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=True),
    sa.Column('average_time_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_question_active', 'questions', ['is_active', 'is_verified'], unique=False)
    op.create_index('idx_question_lookup', 'questions', ['subject', 'topic', 'grade', 'difficulty_level', 'bloom_level'], unique=False)
    op.create_index(op.f('ix_questions_bloom_level'), 'questions', ['bloom_level'], unique=False)
    op.create_index(op.f('ix_questions_difficulty_level'), 'questions', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_questions_grade'), 'questions', ['grade'], unique=False)
    op.create_index(op.f('ix_questions_subject'), 'questions', ['subject'], unique=False)
    op.create_index(op.f('ix_questions_topic'), 'questions', ['topic'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('bloom_level', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_user_id'), 'quizzes', ['user_id'], unique=False)
    # Note: Keeping assessment tables - they are used by teacher dashboard
    # op.drop_table('assessment_rubrics')
    # op.drop_table('rubric_levels')
    # op.drop_table('assessment_questions')
    # op.drop_table('assessment_attempts')
    # op.drop_table('assessment_responses')
    # op.drop_table('rubric_criteria')
    # op.drop_table('assessments')
    # op.drop_table('assessment_analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_analytics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('total_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('completion_rate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('average_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('average_time_minutes', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('question_analytics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('class_comparisons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('difficulty_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name='assessment_analytics_assessment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assessment_analytics_pkey')
    )
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bloom_levels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('topics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('question_count', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False),
    sa.Column('time_limit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=20), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('assigned_classes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name='assessments_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assessments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('rubric_criteria',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rubric_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['assessment_rubrics.id'], name='rubric_criteria_rubric_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rubric_criteria_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('assessment_responses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attempt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('points_earned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('time_taken_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_flagged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('teacher_comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], name='assessment_responses_attempt_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], name='assessment_responses_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assessment_responses_pkey')
    )
    op.create_table('assessment_attempts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time_taken_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('max_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_submitted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_graded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('graded_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('graded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('teacher_feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rubric_scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name='assessment_attempts_assessment_id_fkey'),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], name='assessment_attempts_graded_by_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='assessment_attempts_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assessment_attempts_pkey')
    )
    op.create_table('assessment_questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('correct_answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bloom_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name='assessment_questions_assessment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assessment_questions_pkey')
    )
    op.create_table('rubric_levels',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('criterion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['rubric_criteria.id'], name='rubric_levels_criterion_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rubric_levels_pkey')
    )
    op.create_table('assessment_rubrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name='assessment_rubrics_assessment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assessment_rubrics_pkey')
    )
    op.drop_index(op.f('ix_quizzes_user_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_questions_topic'), table_name='questions')
    op.drop_index(op.f('ix_questions_subject'), table_name='questions')
    op.drop_index(op.f('ix_questions_grade'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty_level'), table_name='questions')
    op.drop_index(op.f('ix_questions_bloom_level'), table_name='questions')
    op.drop_index('idx_question_lookup', table_name='questions')
    op.drop_index('idx_question_active', table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###